congestion + join on here names #16
CityofToronto/bdit_tt_request_app pull request #37
Opened 2023-04-14 18:09 UTC by tankedman

2023-04-18 14:31 UTC, Nate-Wessel requested changes

2023-04-18 14:31 UTC, Nate-Wessel commented on backend/app/routes.py
> +                    JOIN here.routing_nodes_intersec_name ON congestion.network_nodes.node_id = here.routing_nodes_intersec_name.node_id
Simplify this join with `USING ( node_id )`. That will make it easier to read.

2023-04-18 14:31 UTC, Nate-Wessel commented on backend/app/routes.py
> +            print(nodes_ascend_dist_order_query_result)
remove print statement

2023-04-18 14:31 UTC, Nate-Wessel commented on backend/app/routes.py
>      with connection:
You can actually do this in one line:
 `with getConnection() as connection:`

Pretty sure you still need to explicitly close it though.

2023-04-18 14:31 UTC, Nate-Wessel commented on backend/app/routes.py
>              nodes_ascend_dist_order_query_result = cursor.fetchall()
Instead of storing this in this super-long variable, can we just iterate over the cursor results directly? e.g. 

```python
for node_id, stname, coord_dict, distance in cursor.fetchall():
```

2023-04-18 15:16 UTC, tankedman commented on backend/app/routes.py
>              nodes_ascend_dist_order_query_result = cursor.fetchall()
does this not make a call to fetchall() for every iteration of the loop?

2023-04-18 15:18 UTC, Nate-Wessel commented on backend/app/routes.py
>              nodes_ascend_dist_order_query_result = cursor.fetchall()
No, I'm pretty sure it just returns a list once.

2023-04-18 16:54 UTC, Nate-Wessel commented
Resolves https://github.com/CityofToronto/bdit_tt_request_app/issues/16

2023-04-19 15:31 UTC, Nate-Wessel requested changes

2023-04-19 15:31 UTC, Nate-Wessel commented on backend/app/routes.py
> +                    JOIN USING (node_id)
JOIN _what_ USING( node_id) ?

2023-04-19 16:17 UTC, Nate-Wessel requested changes

2023-04-19 16:17 UTC, Nate-Wessel commented on backend/app/routes.py
> +    for node_id, stname, coord_dict, distance in cursor.fetchall():
This needs to be indented. The cursor is already closed at this point

2023-04-19 20:08 UTC, merged